services:
  core:
    container_name: chainCore
    restart:  always
    build:
      context: .
      dockerfile: ./apps/core/Dockerfile
      target: production
    command: npm run start core
    env_file:
      - ./apps/core/.production.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '7001:7001'
volumes:
  mongodb_master_data:
    driver: local
